name: Generate code coverage badge

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Update coverage badge
    steps:
      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
            report: true
            chart: true
            amend: true
        continue-on-error: false